### ISSUE TITLE
[DB][Design] Create db tables relation schema

### ISSUE THREAD

**Issue by noharagg** [efremnikolaus/emergency-notification-system#2]
1) please create a schema of db relation.
2) add all relationships between tables and their columns with data types
3) use in database design the concept of normalization https://habr.com/ru/articles/254773/

**Comment by efremnikolaus** [comment]
I made a preliminary schematic, the so-called stub, with time needs work.
![Emergency Notification System](https://github.com/efremnikolaus/emergency-notification-system/assets/113909980/f09ef150-c8eb-4c4f-bebe-2222781691db)

**Comment by noharagg** [comment]
approved
